### ISSUE TITLE
Incorrect initial value; should be FFFFFFFF not 0

### ISSUE THREAD

**Issue by snej** [juancarlospaco/nim-crc32#2]
FYI, your implementation starts with the wrong initial value. It should be 0xFFFFFFFF, not 0.

https://github.com/juancarlospaco/nim-crc32/blob/a66d7087a9e89651bbd54802f97fcf51567624d3/src/crc32.nim#L11

If you're only using your own code to both generate and check CRCs this isn't a problem, but if you want to verify digests generated by anyone else (or vice versa), this would need to be fixed.

I've made this change in my own forked code and can attest that it works correctly (at least that it matches values generated by the `crc32` function in zlib.)

**Comment by juancarlospaco** [comment]
@snej
Send PR gonna Merge.

**Comment by snej** [comment]
It's a less-than-one-line change for you to make, and I don't have a fork of your repo to send a PR from (I ended up switching to the `crc32` function in the zip package.)
